# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='checklist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='constructionCheck.Checklist'),
        ),
    ]
